// Auto-generated legacy text → code map
export const LEGACY_TEXT_TO_CODE: Record<string, string> = {
  "AFFILIATE_NOT_FOUND": "affiliateNotFound",
  "Affiliate code not found": "affiliateNotFound",
  "client_key_required": "clientKeyRequired",
  "Client key is required": "clientKeyRequired",
  "COUPON_ONE_ONLY": "couponOneOnly",
  "Only one coupon can be applied per order": "couponOneOnly",
  "INTERNAL_ERROR": "internalError",
  "An error occurred": "internalError",
  "INVALID_REQUEST": "invalidRequest",
  "Invalid request": "invalidRequest",
  "MaxBackupsReached": "maxBackupsReached",
  "Maximum number of backups reached": "errorMaxBackupsReached",
  "REGISTRATION_DISABLED_BUSINESS": "registrationDisabledBusiness",
  "Registration for business accounts is currently disabled": "registrationDisabledBusiness",
  "REGISTRATION_DISABLED_GENERAL": "registrationDisabledGeneral",
  "Registration is currently disabled": "registrationDisabledGeneral",
  "REGISTRATION_DISABLED_PRIVATE": "registrationDisabledPrivate",
  "Registration for private accounts is currently disabled": "registrationDisabledPrivate",
  "NAME_ADDRESS_AUTOMATED_CHECK_DECLINED": "nameAddressAutomatedCheckDeclined",
  "We do not issue invoices to this addressee.": "nameAddressAutomatedCheckDeclined",
  "bonusAlreadyUsed": "bonusAlreadyUsed",
  "The 7-day bonus has already been used for this service": "bonusAlreadyUsed",
  "billingCycleNotAllowed": "billingCycleNotAllowed",
  "Billing cycle is not allowed for this product": "billingCycleNotAllowed",
  "downgradeApplyError": "downgradeApplyError",
  "Failed to apply downgrade": "downgradeApplyError",
  "downgradeMissingParams": "downgradeMissingParams",
  "resourceChanges is required": "downgradeMissingParams",
  "downgradeNoSubscription": "downgradeNoSubscription",
  "No subscription for this service": "downgradeNoSubscription",
  "downgradeNotApplicable": "downgradeNotApplicable",
  "No downgrade applicable": "downgradeNotApplicable",
  "downgradeServiceNotFound": "downgradeServiceNotFound",
  "Service not found": "serviceNotFound",
  "email_in_use": "emailInUse",
  "Email is already in use": "emailInUse",
  "errorBackupRateLimit": "errorBackupRateLimit",
  "Too many backup requests. Please wait a few minutes and try again.": "errorBackupRateLimit",
  "errorMaxBackupsReached": "errorMaxBackupsReached",
  "expired": "expired",
  "Code expired": "expired",
  "feedbackExactlyOneLink": "feedbackExactlyOneLink",
  "Select either ticket or service, not both": "feedbackExactlyOneLink",
  "feedbackGeneralCooldown": "feedbackGeneralCooldown",
  "General feedback can only be submitted every 4 weeks": "feedbackGeneralCooldown",
  "feedbackTicketOrServiceRequired": "feedbackTicketOrServiceRequired",
  "Ticket or service required": "feedbackTicketOrServiceRequired",
  "invalidBillingCycle": "invalidBillingCycle",
  "Invalid billing cycle": "invalidBillingCycle",
  "invalidBillingCycleDays": "invalidBillingCycleDays",
  "Invalid billing cycle days": "invalidBillingCycleDays",
  "invalidPrice": "invalidPrice",
  "Invalid price": "invalidPrice",
  "invoiceAlreadyPaid": "invoiceAlreadyPaid",
  "Invoice is already paid": "invoiceAlreadyPaid",
  "ipCancelAlreadyScheduled": "ipCancelAlreadyScheduled",
  "Cancellation already scheduled": "ipCancelAlreadyScheduled",
  "ipCancelNoSubscription": "ipCancelNoSubscription",
  "No active subscription found": "ipCancelNoSubscription",
  "ipCancelNotAllowed": "ipCancelNotAllowed",
  "IP cannot be cancelled": "ipCancelNotAllowed",
  "ipCancelNotFound": "ipCancelNotFound",
  "No scheduled cancellation found": "ipCancelNotFound",
  "ipCancelPeriodEnded": "ipCancelPeriodEnded",
  "Current period already ended": "ipCancelPeriodEnded",
  "ipCancelPrimaryNotAllowed": "ipCancelPrimaryNotAllowed",
  "Primary IP cannot be cancelled": "ipCancelPrimaryNotAllowed",
  "loyaltyOfferNotAvailable": "loyaltyOfferNotAvailable",
  "Loyalty offer is not available for this subscription": "loyaltyOfferNotAvailable",
  "max_attempts": "maxAttempts",
  "Maximum number of attempts reached": "maxAttempts",
  "no_pending": "noPending",
  "No pending request found": "noPending",
  "notPendingCancellation": "notPendingCancellation",
  "Subscription is not scheduled for cancellation": "notPendingCancellation",
  "password_wrong": "passwordWrong",
  "Password is incorrect": "passwordWrong",
  "paymentAlreadyInProgress": "paymentAlreadyInProgress",
  "A payment is already in progress for this invoice": "paymentAlreadyInProgress",
  "periodExpired": "periodExpired",
  "Current period has already expired": "periodExpired",
  "rate_limited": "rateLimited",
  "Too many requests. Please wait a moment.": "rateLimited",
  "same_email": "sameEmail",
  "New email address matches the current one": "sameEmail",
  "serviceCancelled": "serviceCancelled",
  "Service has been cancelled": "serviceCancelled",
  "serviceNoProviderMapping": "serviceNoProviderMapping",
  "Service has no provider mapping": "serviceNoProviderMapping",
  "serviceNotFound": "serviceNotFound",
  "subscriptionAlreadyCanceled": "subscriptionAlreadyCanceled",
  "Subscription already canceled": "subscriptionAlreadyCanceled",
  "subscriptionCanceling": "subscriptionCanceling",
  "Cannot change interval when subscription is set to cancel": "subscriptionCanceling",
  "subscriptionNotActive": "subscriptionNotActive",
  "Subscription is not active": "subscriptionNotActive",
  "subscriptionNotFound": "subscriptionNotFound",
  "Subscription not found": "subscriptionNotFound",
  "checkoutDomainBusinessfundNotAllowed": "checkoutDomainBusinessfundNotAllowed",
  "Domain orders cannot be paid via Businessfund.": "checkoutDomainBusinessfundNotAllowed",
  "checkoutDomainSingleItemOnly": "checkoutDomainSingleItemOnly",
  "Domain orders must be paid as a single-item checkout.": "checkoutDomainSingleItemOnly",
  "checkoutDomainInvalid": "checkoutDomainInvalid",
  "Invalid domain": "checkoutDomainInvalid",
  "checkoutDomainInvalidTerm": "checkoutDomainInvalidTerm",
  "Invalid domain term": "checkoutDomainInvalidTerm",
  "checkoutDomainActionInvalid": "checkoutDomainActionInvalid",
  "Invalid domain action": "checkoutDomainActionInvalid",
  "familyGroupInactive": "familyGroupInactive",
  "Family group not found or inactive": "familyGroupInactive",
  "familyOwnerMissing": "familyOwnerMissing",
  "Family owner not found": "familyOwnerMissing",
  "noFamilyGroup": "noFamilyGroup",
  "No family group found": "noFamilyGroup",
  "familyGroupRequired": "familyGroupRequired",
  "Family group required": "familyGroupRequired",
  "familyConsentRequired": "familyConsentRequired",
  "Parental consent has not been given yet": "familyConsentRequired",
  "familyApprovalRequired": "familyApprovalRequired",
  "Payment requires parental approval": "familyApprovalRequired",
  "familyBudgetExhausted": "familyBudgetExhausted",
  "Child purchase budget exhausted for this period": "familyBudgetExhausted",
  "familyChildPaymentMethodsRestricted": "familyChildPaymentMethodsRestricted",
  "Payment methods are restricted for child accounts": "familyChildPaymentMethodsRestricted",
  "familyAccountLocked": "familyAccountLocked",
  "Account is locked by parental controls": "familyAccountLocked",
  "familyServiceLocked": "familyServiceLocked",
  "Service is locked by parental controls": "familyServiceLocked",
  "familyTimePolicyViolation": "familyTimePolicyViolation",
  "Blocked by time policy": "familyTimePolicyViolation",
  "familyMinorTopupBlocked": "familyMinorTopupBlocked",
  "Children cannot top up balance directly": "familyMinorTopupBlocked",
  "upgradeBelowProductBase": "upgradeBelowProductBase",
  "Value cannot be below the product base": "upgradeBelowProductBase",
  "upgradeMaxIPv6Exceeded": "upgradeMaxIPv6Exceeded",
  "Maximum 30 IPv6 per service": "upgradeMaxIPv6Exceeded",
  "upgradeMaxIpsExceeded": "upgradeMaxIpsExceeded",
  "Maximum 10 IPv4 per service (including primary IP)": "upgradeMaxIpsExceeded",
  "upgradeNoChangesApplicable": "upgradeNoChangesApplicable",
  "No upgrade or downgrade applicable for the given changes": "upgradeNoChangesApplicable",
  "upgradeNotAllowed": "upgradeNotAllowed",
  "Upgrade or downgrade is not allowed for this product": "upgradeNotAllowed",
  "upgradeRequiresCheckout": "upgradeRequiresCheckout",
  "This upgrade requires checkout": "upgradeRequiresCheckout",
  "upgradeStorageInsufficient": "upgradeStorageInsufficient",
  "Insufficient storage space on disk for upgrade": "upgradeStorageInsufficient",
  "upgradeStorageStepInvalid": "upgradeStorageStepInvalid",
  "Storage must use a valid increment": "upgradeStorageStepInvalid",
  "renewalExceedsMaxRuntime": "renewalExceedsMaxRuntime",
  "Renewal exceeds the maximum runtime": "renewalExceedsMaxRuntime",
  "wrong_code": "wrongCode",
  "Wrong code": "wrongCode",
  "Access denied": "accessDenied",
  "Account activated successfully.": "accountActivatedSuccessfully",
  "Account already linked to this provider": "accountAlreadyLinkedToThisProvider",
  "Account holder name is required": "accountHolderNameIsRequired",
  "Account is already verified.": "accountIsAlreadyVerified",
  "Account is not active": "accountIsNotActive",
  "Account not linked to this provider": "accountNotLinkedToThisProvider",
  "Address ID is required": "addressIdIsRequired",
  "Address not found": "addressNotFound",
  "At least one address is required": "atLeastOneAddressIsRequired",
  "Admin access required": "adminAccessRequired",
  "Affiliate-Code erforderlich": "affiliateCodeIsRequired",
  "Affiliate-Code nicht gefunden": "affiliateCodeNotFound",
  "A new activation code has been sent to your email.": "aNewActivationCodeHasBeenSentToYourEmail",
  "A pending payout request already exists": "aPendingPayoutRequestAlreadyExists",
  "Active auto top-ups must be recreated to change the amount": "activeAutoTopUpsMustBeRecreatedToChangeTheAmount",
  "Amount and binding period are required": "amountAndBindingPeriodAreRequired",
  "An auto top-up for this day already exists": "anAutoTopUpForThisDayAlreadyExists",
  "Amount exceeds withdrawable balance": "amountExceedsWithdrawableBalance",
  "API key revoked successfully": "apiKeyRevokedSuccessfully",
  "At least one document is required": "atLeastOneDocumentIsRequired",
  "Authentication failed": "authenticationFailed",
  "Backup codes regenerated successfully": "backupCodesRegeneratedSuccessfully",
  "Backup deleted": "backupDeleted",
  "Backup deletion not supported for this provider": "backupDeletionNotSupportedForThisProvider",
  "Backup download not supported for this provider": "backupDownloadNotSupportedForThisProvider",
  "Backup restore not supported for this provider": "backupRestoreNotSupportedForThisProvider",
  "Backups not supported for this provider": "backupsNotSupportedForThisProvider",
  "Billing address is required": "billingAddressIsRequired",
  "Billing address not found": "billingAddressNotFound",
  "Billing address not found or unauthorized": "billingAddressNotFoundOrUnauthorized",
  "Default address cannot be deleted": "defaultAddressCannotBeDeleted",
  "Default address cannot be unset": "defaultAddressCannotBeUnset",
  "Billing cycle change scheduled for next period": "billingIntervalChangeScheduledForNextPeriod",
  "Billing email already verified": "billingEmailAlreadyVerified",
  "Billing email cannot be the same as account email": "billingEmailCannotBeTheSameAsAccountEmail",
  "Billing email has been changed or removed": "billingEmailHasBeenChangedOrRemoved",
  "Calculation failed": "calculationFailed",
  "Cannot revoke current session. Use logout instead.": "cannotRevokeCurrentSessionUseLogoutInstead",
  "Cannot grant permission to yourself": "cannotGrantPermissionToYourself",
  "Category and rating are required": "categoryAndRatingAreRequired",
  "Category ID required": "categoryIdRequired",
  "Category not found": "categoryNotFound",
  "Checkout already in progress": "checkoutAlreadyInProgress",
  "Checkout failed": "checkoutFailed",
  "Code has already been used": "codeHasAlreadyBeenUsed",
  "Code has expired": "codeHasExpired",
  "Code is required": "codeIsRequired",
  "Company name and VAT number are only available for business accounts": "companyNameAndVatNumberAreOnlyAvailableForBusinessAccounts",
  "Company name is required for business accounts": "companyNameIsRequiredForBusinessAccounts",
  "Console not available for this service": "consoleNotAvailableForThisService",
  "Console streaming only supported for Pterodactyl services": "consoleStreamingOnlySupportedForPterodactylServices",
  "dateOfBirth is required": "dateOfBirthIsRequired",
  "Date of birth cannot be in the future": "dateOfBirthCannotBeInTheFuture",
  "Date of birth is already set and cannot be changed": "dateOfBirthIsAlreadySetAndCannotBeChanged",
  "DOB_ALREADY_SET": "dateOfBirthIsAlreadySetAndCannotBeChanged2",
  "Invalid date format": "invalidDateFormat",
  "Invalid date of birth": "invalidDateOfBirth",
  "Proxmox cluster not configured": "proxmoxClusterNotConfigured",
  "Proxmox host not in trusted domains": "proxmoxHostNotInTrustedDomains",
  "Current password and new password are required": "currentPasswordAndNewPasswordAreRequired",
  "Current password is incorrect": "currentPasswordIsIncorrect",
  "Current password is required": "currentPasswordIsRequired",
  "Dieser Gutschein ist abgelaufen.": "thisVoucherHasExpired",
  "Dieser Gutschein wurde bereits eingelöst.": "thisVoucherHasAlreadyBeenRedeemed",
  "Direct upgrades are not supported. Please use the cart/checkout flow to upgrade your service.": "directUpgradesAreNotSupportedPleaseUseTheCartCheckoutFlowToUpgrade",
  "Document not found": "documentNotFound",
  "Downgrade applied": "downgradeApplied",
  "Email already in use": "emailAlreadyInUse",
  "Email and code required": "emailAndCodeRequired",
  "Email and password are required": "emailAndPasswordAreRequired",
  "Email does not match code": "emailDoesNotMatchCode",
  "Email is already verified": "emailIsAlreadyVerified",
  "Email is required": "emailIsRequired",
  "Email verified successfully": "emailVerifiedSuccessfully",
  "Ein Fehler ist aufgetreten": "anErrorOccurred",
  "Einige Produkte sind derzeit nicht verfügbar (ausverkauft). Bitte entferne sie aus dem Warenkorb.": "someProductsAreCurrentlyUnavailableSoldOutPleaseRemoveThemFromYour",
  "Es kann nur ein Coupon pro Bestellung angewendet werden": "onlyOneCouponCanBeAppliedPerOrder",
  "Extension applied directly (admin — no invoice).": "extensionAppliedDirectlyAdminNoInvoice",
  "Failed to create address": "failedToCreateAddress",
  "Failed to delete account": "failedToDeleteAccount",
  "Failed to delete address": "failedToDeleteAddress",
  "Failed to fetch addresses": "failedToFetchAddresses",
  "Failed to fetch countries": "failedToFetchCountries",
  "Failed to generate GDPR export": "failedToGenerateGdprExport",
  "Failed to get console access": "failedToGetConsoleAccess",
  "Console not available while server is being set up": "consoleNotAvailableWhileServerIsBeingSetUp",
  "Console temporarily unavailable, please try again": "consoleTemporarilyUnavailablePleaseTryAgain",
  "Failed to get sessions": "failedToGetSessions",
  "Failed to initiate email change": "failedToInitiateEmailChange",
  "Failed to load settings": "failedToLoadSettings",
  "Failed to process request": "failedToProcessRequest",
  "Failed to remove billing email": "failedToRemoveBillingEmail",
  "Failed to resend verification email": "failedToResendVerificationEmail",
  "Failed to revoke session": "failedToRevokeSession",
  "Failed to send code": "failedToSendCode",
  "Failed to send verification email": "failedToSendVerificationEmail",
  "Failed to update address": "failedToUpdateAddress",
  "Failed to update autopay settings": "failedToUpdateAutopaySettings",
  "Failed to update billing address": "failedToUpdateBillingAddress",
  "Failed to cancel Mollie subscription": "failedToCancelMollieSubscription",
  "Failed to revoke Mollie mandate": "failedToRevokeMollieMandate",
  "Failed to update settings": "failedToUpdateSettings",
  "Failed to verify billing email": "failedToVerifyBillingEmail",
  "Failed to verify code": "failedToVerifyCode",
  "First name and last name are required": "firstNameAndLastNameAreRequired",
  "If an account with that email exists, we've sent a password reset link.": "ifAnAccountWithThatEmailExistsWeVeSentAPasswordResetLink",
  "If the email exists, a code has been sent": "ifTheEmailExistsACodeHasBeenSent",
  "Incorrect password": "incorrectPassword",
  "Insufficient balance": "insufficientBalance",
  "Internal server error": "internalServerError",
  "Invalid amount": "invalidAmount",
  "Invalid billingCycleDays. Allowed: 7, 14, 30, 60, 90, 120, 365": "invalidBillingCycleDaysAllowed714306090120365",
  "Invalid or expired code. Please request a new one.": "invalidOrExpiredCodePleaseRequestANewOne",
  "Invalid or expired verification link": "invalidOrExpiredVerificationLink",
  "Invalid email address": "invalidEmailAddress",
  "Invalid email format": "invalidEmailFormat",
  "Invalid email or password": "invalidEmailOrPassword",
  "Invalid JSON body": "invalidJsonBody",
  "Invalid language": "invalidLanguage",
  "Invalid or expired code": "invalidOrExpiredCode",
  "Invalid or expired reset link": "invalidOrExpiredResetLink",
  "Invalid password": "invalidPassword",
  "Invalid payout method type. Must be PAYPAL or SEPA.": "invalidPayoutMethodTypeMustBePaypalOrSepa",
  "Invalid request body": "invalidRequestBody",
  "Invalid session": "invalidSession",
  "Invalid VAT ID format. Example: DE123456789": "invalidVatIdFormatExampleDe123456789",
  "Invalid verification code": "invalidVerificationCode",
  "Invalid verification code. Please try again.": "invalidVerificationCodePleaseTryAgain",
  "Invalid verification token": "invalidVerificationToken",
  "Logged in successfully": "loggedInSuccessfully",
  "Logged out successfully": "loggedOutSuccessfully",
  "Mail service is not enabled": "mailServiceIsNotEnabled",
  "Maximum of 4 auto top-up configs allowed": "maximumOf4AutoTopUpConfigsAllowed",
  "Message is required": "messageIsRequired",
  "Missing 'command' field": "missingCommandField",
  "Missing payment ID": "missingPaymentId",
  "Missing required fields": "missingRequiredFields",
  "Name is required": "nameIsRequired",
  "Name must be 100 characters or less": "nameMustBe100CharactersOrLess",
  "New password must be at least 8 characters long": "newPasswordMustBeAtLeast8CharactersLong",
  "New password must be different from current password": "newPasswordMustBeDifferentFromCurrentPassword",
  "Newsletter opt-out successful": "newsletterOptOutSuccessful",
  "No active subscription found for this service": "noActiveSubscriptionFoundForThisService",
  "No items": "noItems",
  "No provider available for this product": "noProviderAvailableForThisProduct",
  "No valid fields to update": "noValidFieldsToUpdate",
  "No verification challenge found. Please try again.": "noVerificationChallengeFoundPleaseTryAgain",
  "Not authenticated": "notAuthenticated",
  "Password changed successfully": "passwordChangedSuccessfully",
  "Password change failed": "passwordChangeFailed",
  "Password confirmation required for account deletion": "passwordConfirmationRequiredForAccountDeletion",
  "Password login not available for this account": "passwordLoginNotAvailableForThisAccount",
  "Password must be at least 8 characters long": "passwordMustBeAtLeast8CharactersLong",
  "Password must contain uppercase, lowercase, and a number": "passwordMustContainUppercaseLowercaseAndANumber",
  "Password reset successfully. Please log in with your new password.": "passwordResetSuccessfullyPleaseLogInWithYourNewPassword",
  "Passkey deleted successfully": "passkeyDeletedSuccessfully",
  "Passkey not recognized": "passkeyNotRecognized",
  "Passkey registered successfully": "passkeyRegisteredSuccessfully",
  "Passkey verification failed": "passkeyVerificationFailed",
  "Payment methods feature has been deprecated. Use account balance for autopay instead.": "paymentMethodsFeatureHasBeenDeprecatedUseAccountBalanceForAutopayIns",
  "Mollie customer not found": "mollieCustomerNotFound",
  "Mollie payment created but no checkout URL returned": "molliePaymentCreatedButNoCheckoutUrlReturned",
  "Payment service is not available": "paymentServiceIsNotAvailable",
  "Please enter the 6-digit code from your email.": "pleaseEnterThe6DigitCodeFromYourEmail",
  "Please fill in your address in your profile settings first": "pleaseFillInYourAddressInYourProfileSettingsFirst",
  "Please fill in your city in your profile settings first": "pleaseFillInYourCityInYourProfileSettingsFirst",
  "Please fill in your ZIP code in your profile settings first": "pleaseFillInYourZipCodeInYourProfileSettingsFirst",
  "Please set your company name in your profile settings first": "pleaseSetYourCompanyNameInYourProfileSettingsFirst",
  "Please set your country in your profile settings first": "pleaseSetYourCountryInYourProfileSettingsFirst",
  "Please set your display name in your profile settings first": "pleaseSetYourDisplayNameInYourProfileSettingsFirst",
  "Registration failed": "registrationFailed",
  "Registration successful. Please check your email and enter the activation code.": "registrationSuccessfulPleaseCheckYourEmailAndEnterTheActivationCode",
  "Reactivate this auto top-up by creating a new one": "reactivateThisAutoTopUpByCreatingANewOne",
  "Service deletion scheduled": "serviceDeletionScheduled",
  "Service is suspended": "serviceIsSuspended",
  "Session ID required": "sessionIdRequired",
  "Session not found": "sessionNotFound",
  "Session revoked successfully. That device has been logged out.": "sessionRevokedSuccessfullyThatDeviceHasBeenLoggedOut",
  "SEPA details not configured": "sepaDetailsNotConfigured",
  "SEPA top-up is not available": "sepaTopUpIsNotAvailable",
  "Staff access required": "staffAccessRequired",
  "Storage added to cart": "storageAddedToCart",
  "Storage subscription canceled immediately": "storageSubscriptionCanceledImmediately",
  "Storage subscription will cancel at end of billing period": "storageSubscriptionWillCancelAtEndOfBillingPeriod",
  "Storage volume deleted": "storageVolumeDeleted",
  "Subscription canceled immediately": "subscriptionCanceledImmediately",
  "Subscription reactivated — auto-renew re-enabled": "subscriptionReactivatedAutoRenewReEnabled",
  "Subscription will cancel at end of billing period": "subscriptionWillCancelAtEndOfBillingPeriod",
  "This account uses social login. You can set a password by using 'Forgot Password'.": "thisAccountUsesSocialLoginYouCanSetAPasswordByUsingForgotPassword",
  "This code has expired. Please request a new one.": "thisCodeHasExpiredPleaseRequestANewOne",
  "This route cannot be accessed with an API key": "thisRouteCannotBeAccessedWithAnApiKey",
  "Day of month must be between 1 and 28": "dayOfMonthMustBeBetween1And28",
  "Too-factor authentication code required": "twoFactorAuthenticationCodeRequired",
  "TOTP authenticator is not set up": "totpAuthenticatorIsNotSetUp",
  "TOTP authenticator disabled successfully": "totpAuthenticatorDisabledSuccessfully",
  "Two-factor authentication code required": "twoFactorAuthenticationCodeRequired2",
  "Two-factor authentication enabled successfully": "twoFactorAuthenticationEnabledSuccessfully",
  "Unauthorized": "unauthorized",
  "Ungültiger Bestellwert": "invalidOrderAmount",
  "Unknown error": "genericError",
  "Upgrade/Downgrade/Renewal-Items erfordern serviceId oder subscriptionId": "upgradeDowngradeAndRenewalItemsRequireAServiceIdOrSubscriptionId",
  "User not found": "userNotFound",
  "Valid amount required": "validAmountRequired",
  "Valid email is required": "validEmailIsRequired",
  "Validation failed": "validationFailed",
  "Validation failed for egg variables": "validationFailedForEggVariables",
  "Validation failed for provider egg variables": "validationFailedForProviderEggVariables",
  "Verification code sent to email": "verificationCodeSentToEmail",
  "Verification email sent": "verificationEmailSent",
  "Verification email sent. Please check your inbox.": "verificationEmailSentPleaseCheckYourInbox",
  "Verification failed": "verificationFailed",
  "Verification link has expired. Please request a new one.": "verificationLinkHasExpiredPleaseRequestANewOne",
  "Verification token is required": "verificationTokenIsRequired",
  "You can only view your own invoices": "youCanOnlyViewYourOwnInvoices",
  "Your account has been suspended. Please contact support.": "yourAccountHasBeenSuspendedPleaseContactSupport",
  "You have no permission for this service": "youHaveNoPermissionForThisService",
  "Sie haben keine Berechtigung für diese Subscription": "youDoNotHavePermissionForThisSubscription",
  "Sie haben keine Berechtigung für diesen Service": "youDoNotHavePermissionForThisService",
  "dateOfBirthMissingInProfile": "dateOfBirthMissingInProfile",
  "Geburtsdatum fehlt im Profil.": "dateOfBirthMissingInProfile",
  "Date of birth is missing from your profile.": "dateOfBirthMissingInProfile",
  "identVerificationMinAge18": "identVerificationMinAge18",
  "Identitätsverifikation ist erst ab 18 Jahren möglich.": "identVerificationMinAge18",
  "Identity verification is only available from age 18.": "identVerificationMinAge18",
  "identAlreadyVerified": "identAlreadyVerified",
  "Ihre Identität ist bereits verifiziert.": "identAlreadyVerified",
  "Your identity is already verified.": "identAlreadyVerified",
  "identVerificationCountryRequired": "identVerificationCountryRequired",
  "Mindestens ein freigegebenes Land muss für die Verifikation aktiviert sein.": "identVerificationCountryRequired",
  "At least one approved country must be enabled for verification.": "identVerificationCountryRequired",
  "identVerificationCountryUnavailable": "identVerificationCountryUnavailable",
  "Verifikation für dieses Land ist nicht verfügbar.": "identVerificationCountryUnavailable",
  "Verification is not available for this country.": "identVerificationCountryUnavailable",
  "unknownDocumentType": "unknownDocumentType",
  "Unbekannter Dokumenttyp.": "unknownDocumentType",
  "Unknown document type.": "unknownDocumentType",
  "identVerificationAlreadyPending": "identVerificationAlreadyPending",
  "Es läuft bereits eine Verifikation. Bitte schließen Sie diese ab oder lehnen Sie sie ab.": "identVerificationAlreadyPending",
  "A verification is already in progress. Please complete or decline it.": "identVerificationAlreadyPending",
  "enjynInvalidDateOfBirth": "enjynInvalidDateOfBirth",
  "Enjyn-Ergebnis enthält kein gültiges Geburtsdatum.": "enjynInvalidDateOfBirth",
  "Enjyn result does not contain a valid date of birth.": "enjynInvalidDateOfBirth",
  "identManualUploadNotAvailable": "identManualUploadNotAvailable",
  "Manueller Upload ist für diese Verifikation nicht verfügbar.": "identManualUploadNotAvailable",
  "Manual upload is not available for this verification.": "identManualUploadNotAvailable",
  "identSelectCountryAndDocTypeFirst": "identSelectCountryAndDocTypeFirst",
  "Bitte wählen Sie zuerst Land und Dokumenttyp.": "identSelectCountryAndDocTypeFirst",
  "Please select country and document type first.": "identSelectCountryAndDocTypeFirst",
  "identInvalidImageFormat": "identInvalidImageFormat",
  "Ungültiges Bildformat ({label}). Erlaubt: PNG, JPEG.": "identInvalidImageFormat",
  "Invalid image format ({label}). Allowed: PNG, JPEG.": "identInvalidImageFormat",
  "identImageTooLarge": "identImageTooLarge",
  "Bild zu groß ({label}). Maximal 10 MB.": "identImageTooLarge",
  "Image too large ({label}). Maximum 10 MB.": "identImageTooLarge",
  "identImageContentMismatch": "identImageContentMismatch",
  "Bildinhalt stimmt nicht mit dem Format überein ({label}).": "identImageContentMismatch",
  "Image content does not match the format ({label}).": "identImageContentMismatch",
  "identVerificationNotFoundOrCompleted": "identVerificationNotFoundOrCompleted",
  "Verifikation nicht gefunden oder bereits abgeschlossen.": "identVerificationNotFoundOrCompleted",
  "Verification not found or already completed.": "identVerificationNotFoundOrCompleted",
  "identVerificationFullNameRequired": "identVerificationFullNameRequired",
  "Ihr vollständiger Name ist erforderlich.": "identVerificationFullNameRequired",
  "Your full name is required.": "identVerificationFullNameRequired",
  "identSelectMinorOrAdult": "identSelectMinorOrAdult",
  "Bitte wählen Sie Minderjährig oder Volljährig.": "identSelectMinorOrAdult",
  "Please select minor or adult.": "identSelectMinorOrAdult",
  "identVerificationCannotBeDeclined": "identVerificationCannotBeDeclined",
  "Diese Verifikation kann nicht abgelehnt werden.": "identVerificationCannotBeDeclined",
  "This verification cannot be declined.": "identVerificationCannotBeDeclined",
  "identVerificationPendingExists": "identVerificationPendingExists",
  "Es läuft bereits eine ausstehende Verifikation.": "identVerificationPendingExists",
  "A pending verification already exists.": "identVerificationPendingExists",
  "identUserDataIncomplete": "identUserDataIncomplete",
  "Nutzer-Stammdaten unvollständig für Verifikationsanfrage.": "identUserDataIncomplete",
  "User profile data is incomplete for verification request.": "identUserDataIncomplete",
  "enjynSessionCreateFailed": "enjynSessionCreateFailed",
  "Enjyn-Session konnte nicht erstellt werden.": "enjynSessionCreateFailed",
  "Enjyn session could not be created.": "enjynSessionCreateFailed",
  "enjynIncompleteResponse": "enjynIncompleteResponse",
  "Enjyn-Antwort unvollständig (session_id oder verify_url fehlt).": "enjynIncompleteResponse",
  "Incomplete Enjyn response (session_id or verify_url missing).": "enjynIncompleteResponse",
  "enjynResultFetchFailed": "enjynResultFetchFailed",
  "Enjyn-Ergebnis konnte nicht abgerufen werden.": "enjynResultFetchFailed",
  "Enjyn result could not be retrieved.": "enjynResultFetchFailed",
  "enjynStatusFetchFailed": "enjynStatusFetchFailed",
  "Enjyn-Status konnte nicht abgerufen werden.": "enjynStatusFetchFailed",
  "Enjyn status could not be retrieved.": "enjynStatusFetchFailed",
  "invalidVoucherCode": "invalidVoucherCode",
  "Ungültiger Gutscheincode.": "invalidVoucherCode",
  "Invalid voucher code.": "invalidVoucherCode",
  "voucherCodeNotFound": "voucherCodeNotFound",
  "Gutscheincode nicht gefunden.": "voucherCodeNotFound",
  "Voucher code not found.": "voucherCodeNotFound",
  "voucherCodeNotAvailableAfterRedemption": "voucherCodeNotAvailableAfterRedemption",
  "Code für eingelöste Gutscheine nicht verfügbar.": "voucherCodeNotAvailableAfterRedemption",
  "Code is not available for redeemed vouchers.": "voucherCodeNotAvailableAfterRedemption",
  "familyMinorVoucherPurchaseBlocked": "familyMinorVoucherPurchaseBlocked",
  "Kinder können keine Gutscheine aus Guthaben kaufen.": "familyMinorVoucherPurchaseBlocked",
  "Children cannot purchase vouchers from balance.": "familyMinorVoucherPurchaseBlocked",
  "voucherFaceValueOutOfRange": "voucherFaceValueOutOfRange",
  "Nennwert muss zwischen 0,01 und 100.000 € liegen.": "voucherFaceValueOutOfRange",
  "Face value must be between €0.01 and €100,000.": "voucherFaceValueOutOfRange",
  "voucherTargetUserNotFound": "voucherTargetUserNotFound",
  "Zielnutzer nicht gefunden.": "voucherTargetUserNotFound",
  "Target user not found.": "voucherTargetUserNotFound",
  "identVerificationRequiredForFamily": "identVerificationRequiredForFamily",
  "Identitätsverifikation erforderlich, um eine Familiengruppe anzulegen.": "identVerificationRequiredForFamily",
  "Identity verification is required to create a family group.": "identVerificationRequiredForFamily",
  "minorsCannotCreateFamilyGroups": "minorsCannotCreateFamilyGroups",
  "Minderjährige können keine Familiengruppe anlegen.": "minorsCannotCreateFamilyGroups",
  "Minors cannot create family groups.": "minorsCannotCreateFamilyGroups",
  "userAlreadyOwnsFamilyGroup": "userAlreadyOwnsFamilyGroup",
  "Sie besitzen bereits eine Familiengruppe.": "userAlreadyOwnsFamilyGroup",
  "You already own a family group.": "userAlreadyOwnsFamilyGroup",
  "onlyOwnerCanDissolveFamilyGroup": "onlyOwnerCanDissolveFamilyGroup",
  "Nur der Inhaber kann die Gruppe auflösen.": "onlyOwnerCanDissolveFamilyGroup",
  "Only the owner can dissolve the group.": "onlyOwnerCanDissolveFamilyGroup",
  "cannotDissolveFamilyGroupWithMinorsUnder16": "cannotDissolveFamilyGroupWithMinorsUnder16",
  "Die Gruppe kann nicht aufgelöst werden, solange Minderjährige unter 16 Jahren eine Familiengruppe benötigen.": "cannotDissolveFamilyGroupWithMinorsUnder16",
  "Cannot dissolve the group while it contains minors under 16 who require a family group.": "cannotDissolveFamilyGroupWithMinorsUnder16",
  "familyGroupIsFull": "familyGroupIsFull",
  "Die Familiengruppe ist voll.": "familyGroupIsFull",
  "The family group is full.": "familyGroupIsFull",
  "userAlreadyInFamilyGroup": "userAlreadyInFamilyGroup",
  "Der Nutzer ist bereits in einer Familiengruppe.": "userAlreadyInFamilyGroup",
  "User is already in a family group.": "userAlreadyInFamilyGroup",
  "cannotAssignMinorRoleToAdult": "cannotAssignMinorRoleToAdult",
  "Einem Volljährigen kann keine Minderjährigen-Rolle zugewiesen werden.": "cannotAssignMinorRoleToAdult",
  "Cannot assign MINOR role to an adult.": "cannotAssignMinorRoleToAdult",
  "cannotAssignParentRoleToMinor": "cannotAssignParentRoleToMinor",
  "Einem Minderjährigen kann keine Eltern-Rolle zugewiesen werden.": "cannotAssignParentRoleToMinor",
  "Cannot assign PARENT role to a minor.": "cannotAssignParentRoleToMinor",
  "cannotRemoveFamilyGroupOwner": "cannotRemoveFamilyGroupOwner",
  "Der Gruppeninhaber kann nicht entfernt werden.": "cannotRemoveFamilyGroupOwner",
  "Cannot remove the group owner.": "cannotRemoveFamilyGroupOwner",
  "userNotInFamilyGroup": "userNotInFamilyGroup",
  "Der Nutzer ist nicht in dieser Familiengruppe.": "userNotInFamilyGroup",
  "User is not in this family group.": "userNotInFamilyGroup",
  "minorsUnder16CannotLeaveFamilyGroup": "minorsUnder16CannotLeaveFamilyGroup",
  "Minderjährige unter 16 Jahren können die Familiengruppe nicht selbst verlassen.": "minorsUnder16CannotLeaveFamilyGroup",
  "Minors under 16 cannot leave a family group on their own.": "minorsUnder16CannotLeaveFamilyGroup",
  "onlyParentsCanRemoveMembers": "onlyParentsCanRemoveMembers",
  "Nur Eltern können Mitglieder entfernen.": "onlyParentsCanRemoveMembers",
  "Only parents can remove members.": "onlyParentsCanRemoveMembers",
  "pendingFamilyInviteExists": "pendingFamilyInviteExists",
  "Für diese E-Mail-Adresse existiert bereits eine ausstehende Einladung.": "pendingFamilyInviteExists",
  "A pending invite already exists for this email.": "pendingFamilyInviteExists",
  "familyInviteNotFound": "familyInviteNotFound",
  "Einladung nicht gefunden.": "familyInviteNotFound",
  "Invite not found.": "familyInviteNotFound",
  "familyInviteNoLongerPending": "familyInviteNoLongerPending",
  "Die Einladung ist nicht mehr ausstehend.": "familyInviteNoLongerPending",
  "Invite is no longer pending.": "familyInviteNoLongerPending",
  "familyInviteExpired": "familyInviteExpired",
  "Die Einladung ist abgelaufen.": "familyInviteExpired",
  "Invite has expired.": "familyInviteExpired",
  "familyGroupNoLongerActive": "familyGroupNoLongerActive",
  "Die Familiengruppe ist nicht mehr aktiv.": "familyGroupNoLongerActive",
  "Family group is no longer active.": "familyGroupNoLongerActive",
  "youAreAlreadyInFamilyGroup": "youAreAlreadyInFamilyGroup",
  "Sie sind bereits in einer Familiengruppe.": "youAreAlreadyInFamilyGroup",
  "You are already in a family group.": "youAreAlreadyInFamilyGroup",
  "familyInviteEmailMismatch": "familyInviteEmailMismatch",
  "Diese Einladung wurde an eine andere E-Mail-Adresse gesendet.": "familyInviteEmailMismatch",
  "This invite was sent to a different email address.": "familyInviteEmailMismatch",
  "minorsCannotAcceptParentInvite": "minorsCannotAcceptParentInvite",
  "Minderjährige können keine Eltern-Einladung annehmen.": "minorsCannotAcceptParentInvite",
  "Minors cannot accept a PARENT invite.": "minorsCannotAcceptParentInvite",
  "onlyParentsCanPerformAction": "onlyParentsCanPerformAction",
  "Nur Eltern können diese Aktion ausführen.": "onlyParentsCanPerformAction",
  "Only parents can perform this action.": "onlyParentsCanPerformAction",
  "amountMustBePositive": "amountMustBePositive",
  "Der Betrag muss positiv sein.": "amountMustBePositive",
  "Amount must be positive.": "amountMustBePositive",
  "familyBillingRequestNotFound": "familyBillingRequestNotFound",
  "Anfrage nicht gefunden.": "familyBillingRequestNotFound",
  "Request not found.": "familyBillingRequestNotFound",
  "familyBillingRequestNoLongerPending": "familyBillingRequestNoLongerPending",
  "Die Anfrage ist nicht mehr ausstehend.": "familyBillingRequestNoLongerPending",
  "Request is no longer pending.": "familyBillingRequestNoLongerPending",
  "familySpendingLimitNotFound": "familySpendingLimitNotFound",
  "Ausgabenlimit nicht gefunden.": "familySpendingLimitNotFound",
  "Spending limit not found.": "familySpendingLimitNotFound",
  "familyApprovalNotFoundOrNotPending": "familyApprovalNotFoundOrNotPending",
  "Freigabe nicht gefunden oder nicht mehr ausstehend.": "familyApprovalNotFoundOrNotPending",
  "Approval not found or not pending.": "familyApprovalNotFoundOrNotPending",
  "familyTimePolicyNotFound": "familyTimePolicyNotFound",
  "Zeitregel nicht gefunden.": "familyTimePolicyNotFound",
  "Time policy not found.": "familyTimePolicyNotFound",
  "familyLockNotFound": "familyLockNotFound",
  "Sperre nicht gefunden.": "familyLockNotFound",
  "Lock not found.": "familyLockNotFound",
  "familyResourceLimitNotFound": "familyResourceLimitNotFound",
  "Ressourcenlimit nicht gefunden.": "familyResourceLimitNotFound",
  "Resource limit not found.": "familyResourceLimitNotFound",
  "domainTldNotResolvable": "domainTldNotResolvable",
  "Keine TLD ermittelbar.": "domainTldNotResolvable",
  "TLD could not be determined.": "domainTldNotResolvable",
  "domainTransferNotOffered": "domainTransferNotOffered",
  "Transfer wird für diese Domain/Endung derzeit nicht angeboten.": "domainTransferNotOffered",
  "Transfer is not currently offered for this domain/TLD.": "domainTransferNotOffered",
  "domainCurrentlyUnavailable": "domainCurrentlyUnavailable",
  "Domain aktuell nicht verfügbar.": "domainCurrentlyUnavailable",
  "Domain is currently unavailable.": "domainCurrentlyUnavailable",
  "domainTransferAuthCodeRequired": "domainTransferAuthCodeRequired",
  "Bitte geben Sie einen Authcode (Transfer-Code) an.": "domainTransferAuthCodeRequired",
  "Please provide an auth code (transfer code).": "domainTransferAuthCodeRequired",
  "domainOrderNotFound": "domainOrderNotFound",
  "Domain-Bestellung nicht gefunden.": "domainOrderNotFound",
  "Domain order not found.": "domainOrderNotFound",
  "domainRestoreWindowExpired": "domainRestoreWindowExpired",
  "Restore-Fenster abgelaufen.": "domainRestoreWindowExpired",
  "Restore window has expired.": "domainRestoreWindowExpired",
  "domainRestoreFailed": "domainRestoreFailed",
  "Restore fehlgeschlagen.": "domainRestoreFailed",
  "Restore failed.": "domainRestoreFailed",
  "domainPriceCatalogUnavailable": "domainPriceCatalogUnavailable",
  "Preis-Katalog für diese TLD ist nicht verfügbar.": "domainPriceCatalogUnavailable",
  "Price catalog for this TLD is not available.": "domainPriceCatalogUnavailable",
  "domainActionNotPriced": "domainActionNotPriced",
  "Diese Aktion ist für diese TLD aktuell nicht bepreist.": "domainActionNotPriced",
  "This action is not currently priced for this TLD.": "domainActionNotPriced",
  "domainActionOrderNotFound": "domainActionOrderNotFound",
  "Action-Bestellung nicht gefunden.": "domainActionOrderNotFound",
  "Action order not found.": "domainActionOrderNotFound",
  "domainProviderActionNotSupported": "domainProviderActionNotSupported",
  "Aktion wird vom Provider nicht unterstützt.": "domainProviderActionNotSupported",
  "Action is not supported by the provider.": "domainProviderActionNotSupported",
  "domainOwnerChangeFailed": "domainOwnerChangeFailed",
  "Inhaberwechsel fehlgeschlagen.": "domainOwnerChangeFailed",
  "Owner change failed.": "domainOwnerChangeFailed",
  "domainUpdateFailed": "domainUpdateFailed",
  "Update fehlgeschlagen.": "domainUpdateFailed",
  "Update failed.": "domainUpdateFailed",
  "domainTradeFailed": "domainTradeFailed",
  "Trade fehlgeschlagen.": "domainTradeFailed",
  "Trade failed.": "domainTradeFailed",
  "domainAuth2RequestFailed": "domainAuth2RequestFailed",
  "Auth2-Anforderung fehlgeschlagen.": "domainAuth2RequestFailed",
  "Auth2 request failed.": "domainAuth2RequestFailed",
  "domainUnknownActionType": "domainUnknownActionType",
  "Unbekannter Action-Typ.": "domainUnknownActionType",
  "Unknown action type.": "domainUnknownActionType",
  "byoipInvalidNetworkPrefix": "byoipInvalidNetworkPrefix",
  "Ungültiges Netzwerk-Präfix-Format.": "byoipInvalidNetworkPrefix",
  "Invalid network prefix format.": "byoipInvalidNetworkPrefix",
  "byoipInvalidIpv4PrefixRange": "byoipInvalidIpv4PrefixRange",
  "IPv4-Präfix muss zwischen /8 und /24 liegen.": "byoipInvalidIpv4PrefixRange",
  "IPv4 prefix must be between /8 and /24.": "byoipInvalidIpv4PrefixRange",
  "byoipInvalidIpv6PrefixRange": "byoipInvalidIpv6PrefixRange",
  "IPv6-Präfix muss zwischen /8 und /48 liegen.": "byoipInvalidIpv6PrefixRange",
  "IPv6 prefix must be between /8 and /48.": "byoipInvalidIpv6PrefixRange",
  "byoipDocumentTooLarge": "byoipDocumentTooLarge",
  "Dokumentgröße überschreitet das Limit von 10 MB.": "byoipDocumentTooLarge",
  "Document size exceeds the 10 MB limit.": "byoipDocumentTooLarge",
  "byoipPremiumDdosUnavailable": "byoipPremiumDdosUnavailable",
  "Premium-DDoS-Umschaltung ist derzeit nicht verfügbar.": "byoipPremiumDdosUnavailable",
  "Premium DDoS switch is currently unavailable.": "byoipPremiumDdosUnavailable",
  "byoipInvalidPremiumDdosProvider": "byoipInvalidPremiumDdosProvider",
  "Ungültiger Ziel-Provider für Premium-DDoS.": "byoipInvalidPremiumDdosProvider",
  "Invalid target provider for Premium DDoS.": "byoipInvalidPremiumDdosProvider",
  "byoipAlreadyOnPremiumDdos": "byoipAlreadyOnPremiumDdos",
  "Bereits auf Premium-DDoS.": "byoipAlreadyOnPremiumDdos",
  "Already on Premium DDoS.": "byoipAlreadyOnPremiumDdos",
  "byoipPremiumDdosSwitchFromStandardOnly": "byoipPremiumDdosSwitchFromStandardOnly",
  "Umschaltung nur vom Standard-DDoS-Schutz möglich.": "byoipPremiumDdosSwitchFromStandardOnly",
  "Switch is only possible from standard DDoS protection.": "byoipPremiumDdosSwitchFromStandardOnly",
  "byoipNoPendingPremiumDdosRequest": "byoipNoPendingPremiumDdosRequest",
  "Keine ausstehende Premium-DDoS-Anfrage.": "byoipNoPendingPremiumDdosRequest",
  "No pending Premium DDoS request.": "byoipNoPendingPremiumDdosRequest",
  "byoipNetworkNotOwned": "byoipNetworkNotOwned",
  "Dieses BYOIP-Netzwerk gehört Ihnen nicht.": "byoipNetworkNotOwned",
  "This BYOIP network does not belong to you.": "byoipNetworkNotOwned",
  "serviceNotOwned": "serviceNotOwned",
  "Dieser Service gehört Ihnen nicht.": "serviceNotOwned",
  "This service does not belong to you.": "serviceNotOwned",
  "byoipNetworkProviderMismatchForService": "byoipNetworkProviderMismatchForService",
  "Dieses BYOIP-Netzwerk ist für den Provider dieses Services nicht zulässig.": "byoipNetworkProviderMismatchForService",
  "This BYOIP network is not allowed for this service's provider.": "byoipNetworkProviderMismatchForService",
  "byoipInvalidAssignedPrefix": "byoipInvalidAssignedPrefix",
  "Ungültiges zugewiesenes Präfix-Format.": "byoipInvalidAssignedPrefix",
  "Invalid assigned prefix format.": "byoipInvalidAssignedPrefix",
  "byoipAssignmentNotFound": "byoipAssignmentNotFound",
  "Zuweisung nicht gefunden.": "byoipAssignmentNotFound",
  "Assignment not found.": "byoipAssignmentNotFound",
  "byoipAssignmentNotOwned": "byoipAssignmentNotOwned",
  "Diese Zuweisung gehört Ihnen nicht.": "byoipAssignmentNotOwned",
  "This assignment does not belong to you.": "byoipAssignmentNotOwned",
  "monitoringElizonPlusRequired": "monitoringElizonPlusRequired",
  "Monitoring ist nur mit elizon+ verfügbar.": "monitoringElizonPlusRequired",
  "Monitoring is only available with elizon+.": "monitoringElizonPlusRequired",
  "monitoringInvalidIp": "monitoringInvalidIp",
  "Ungültige IP-Adresse.": "monitoringInvalidIp",
  "Invalid IP address.": "monitoringInvalidIp",
  "monitoringTargetAlreadyExists": "monitoringTargetAlreadyExists",
  "Ziel existiert bereits.": "monitoringTargetAlreadyExists",
  "Target already exists.": "monitoringTargetAlreadyExists",
  "unableToVerifyRequestOrigin": "unableToVerifyRequestOrigin",
  "Die Herkunft der Anfrage konnte nicht verifiziert werden. Bitte versuchen Sie es später erneut.": "unableToVerifyRequestOrigin",
  "Unable to verify request origin. Please try again later.": "unableToVerifyRequestOrigin",
  "byoipNetworkNotPendingReview": "byoipNetworkNotPendingReview",
  "Netzwerk befindet sich nicht in der Prüfung.": "byoipNetworkNotPendingReview",
  "Network is not pending review.": "byoipNetworkNotPendingReview",
  "byoipNetworkMustBeApprovedToGrant": "byoipNetworkMustBeApprovedToGrant",
  "Netzwerk muss den Status APPROVED haben.": "byoipNetworkMustBeApprovedToGrant",
  "Network must be in APPROVED status to grant.": "byoipNetworkMustBeApprovedToGrant",
  "byoipNetworkMustBeActive": "byoipNetworkMustBeActive",
  "Netzwerk muss ACTIVE sein.": "byoipNetworkMustBeActive",
  "Network must be ACTIVE.": "byoipNetworkMustBeActive",
  "monitoringNoIpv6Subnet": "monitoringNoIpv6Subnet",
  "Kein zugewiesenes IPv6-Subnetz für diesen Service.": "monitoringNoIpv6Subnet",
  "No assigned IPv6 subnet found for this service.": "monitoringNoIpv6Subnet",
  "monitoringIpv6OutsideSubnet": "monitoringIpv6OutsideSubnet",
  "IPv6 muss innerhalb eines zugewiesenen Service-Subnetzes liegen.": "monitoringIpv6OutsideSubnet",
  "IPv6 must be within one of your assigned service subnets.": "monitoringIpv6OutsideSubnet",
  "monitoringInvalidTcpPort": "monitoringInvalidTcpPort",
  "Ungültiger TCP-Port.": "monitoringInvalidTcpPort",
  "Invalid TCP port.": "monitoringInvalidTcpPort",
  "monitoringTargetNotFound": "monitoringTargetNotFound",
  "Monitoring-Ziel nicht gefunden.": "monitoringTargetNotFound",
  "Target not found.": "monitoringTargetNotFound",
  "monitoringAutoTargetCannotBeDeleted": "monitoringAutoTargetCannotBeDeleted",
  "AUTO-Ziele können nicht gelöscht werden.": "monitoringAutoTargetCannotBeDeleted",
  "AUTO targets cannot be deleted.": "monitoringAutoTargetCannotBeDeleted",
  "domainRegistrationNotFound": "domainRegistrationNotFound",
  "Domain nicht gefunden.": "domainRegistrationNotFound",
  "Domain not found.": "domainRegistrationNotFound",
  "tooManySubmissions": "tooManySubmissions",
  "Zu viele Einsendungen. Bitte versuchen Sie es später erneut.": "tooManySubmissions",
  "Too many submissions. Please try again later.": "tooManySubmissions",
  "tooManyStatusLookups": "tooManyStatusLookups",
  "Zu viele Statusabfragen. Bitte versuchen Sie es später erneut.": "tooManyStatusLookups",
  "Too many status lookups. Please try again later.": "tooManyStatusLookups",
  "tooManyReports": "tooManyReports",
  "Zu viele Meldungen. Bitte versuchen Sie es später erneut.": "tooManyReports",
  "Too many reports. Please try again later.": "tooManyReports",
  "tooManyTakedownSubmissions": "tooManyTakedownSubmissions",
  "Zu viele Takedown-Einsendungen. Bitte versuchen Sie es später erneut.": "tooManyTakedownSubmissions",
  "Too many takedown submissions. Please try again later.": "tooManyTakedownSubmissions",
  "reportReasonTooShort": "reportReasonTooShort",
  "Begründung muss mindestens 10 Zeichen lang sein.": "reportReasonTooShort",
  "Reason must be at least 10 characters.": "reportReasonTooShort",
  "reportValidEmailRequired": "reportValidEmailRequired",
  "Gültige E-Mail-Adresse des Meldenden ist erforderlich.": "reportValidEmailRequired",
  "Valid reporter email is required.": "reportValidEmailRequired",
  "reportDocumentTooLarge": "reportDocumentTooLarge",
  "Anhang überschreitet das Limit von 5 MB.": "reportDocumentTooLarge",
  "Attached document exceeds 5 MB limit.": "reportDocumentTooLarge",
  "reportInvalidTarget": "reportInvalidTarget",
  "Ziel muss eine gültige IPv4-Adresse, IPv4:Port oder Domain sein.": "reportInvalidTarget",
  "Target must be a valid IPv4 address, IPv4:port or domain.": "reportInvalidTarget",
  "reportInvalidTargetExtended": "reportInvalidTargetExtended",
  "Ziel muss eine gültige IPv4-, IPv6-Adresse oder Domain sein.": "reportInvalidTargetExtended",
  "Target must be a valid IPv4 address, IPv6 address or domain.": "reportInvalidTargetExtended",
  "reportInvalidUrlTarget": "reportInvalidUrlTarget",
  "Ziel muss eine gültige URL oder Domain sein.": "reportInvalidUrlTarget",
  "Target must be a valid URL or domain.": "reportInvalidUrlTarget",
  "reportInvalidCategory": "reportInvalidCategory",
  "Ungültige Kategorie.": "reportInvalidCategory",
  "Invalid category.": "reportInvalidCategory",
  "reportOtherDescriptionRequired": "reportOtherDescriptionRequired",
  "otherDescription ist für die Kategorie OTHER erforderlich.": "reportOtherDescriptionRequired",
  "otherDescription is required for category OTHER.": "reportOtherDescriptionRequired",
  "reportOtherDescriptionTooLong": "reportOtherDescriptionTooLong",
  "otherDescription darf maximal {max} Zeichen lang sein.": "reportOtherDescriptionTooLong",
  "otherDescription must not exceed {max} characters.": "reportOtherDescriptionTooLong",
  "reportConsentRequired": "reportConsentRequired",
  "Erforderliche Einwilligungsbestätigungen fehlen.": "reportConsentRequired",
  "Required consent confirmations are missing.": "reportConsentRequired",
  "consentRecordNotFound": "consentRecordNotFound",
  "Einwilligungsnachweis nicht gefunden.": "consentRecordNotFound",
  "Consent record not found.": "consentRecordNotFound",
  "familyMessageNotFound": "familyMessageNotFound",
  "Nachricht nicht gefunden.": "familyMessageNotFound",
  "Message not found.": "familyMessageNotFound",
  "notAuthorized": "notAuthorized",
  "Nicht berechtigt.": "notAuthorized",
  "Not authorized.": "notAuthorized",
  "mailServiceDisabled": "mailServiceDisabled",
  "Mail-Dienst ist deaktiviert. Aktivieren Sie ihn in den Admin-Einstellungen.": "mailServiceDisabled",
  "Mail service is disabled. Enable it in admin settings.": "mailServiceDisabled",
  "mailServerNotConfigured": "mailServerNotConfigured",
  "Mailserver nicht konfiguriert. SMTP-Einstellungen im Admin-Panel setzen.": "mailServerNotConfigured",
  "Mail server not configured. Set SMTP settings in admin panel.": "mailServerNotConfigured",
  "mailTemplateRenderFailed": "mailTemplateRenderFailed",
  "Systemvorlage konnte nicht gerendert werden: {slug}": "mailTemplateRenderFailed",
  "Failed to render system template: {slug}": "mailTemplateRenderFailed",
  "providerServiceCreatedEmailRenderFailed": "providerServiceCreatedEmailRenderFailed",
  "Provider-Service-erstellt-E-Mail konnte nicht gerendert werden.": "providerServiceCreatedEmailRenderFailed",
  "Failed to render provider service-created email.": "providerServiceCreatedEmailRenderFailed",
  "providerServiceReinstalledEmailRenderFailed": "providerServiceReinstalledEmailRenderFailed",
  "Provider-Service-neuinstalliert-E-Mail konnte nicht gerendert werden.": "providerServiceReinstalledEmailRenderFailed",
  "Failed to render provider service-reinstalled email.": "providerServiceReinstalledEmailRenderFailed",
  "mollieServiceDisabled": "mollieServiceDisabled",
  "Mollie-Dienst ist deaktiviert. Aktivieren Sie ihn in den Admin-Einstellungen.": "mollieServiceDisabled",
  "Mollie service is disabled. Enable it in admin settings.": "mollieServiceDisabled",
  "mollieApiKeyNotConfigured": "mollieApiKeyNotConfigured",
  "Mollie-API-Schlüssel nicht konfiguriert.": "mollieApiKeyNotConfigured",
  "Mollie API key not configured. Set it in admin settings.": "mollieApiKeyNotConfigured",
  "mollieCheckoutUrlMissing": "mollieCheckoutUrlMissing",
  "Mollie-Zahlung erstellt, aber keine Checkout-URL erhalten.": "mollieCheckoutUrlMissing",
  "Mollie payment created but no checkout URL returned.": "mollieCheckoutUrlMissing",
  "lexwareServiceDisabled": "lexwareServiceDisabled",
  "Lexware-Dienst ist deaktiviert.": "lexwareServiceDisabled",
  "Lexware service is disabled. Enable it in admin settings.": "lexwareServiceDisabled",
  "lexwareApiKeyNotConfigured": "lexwareApiKeyNotConfigured",
  "Lexware-API-Schlüssel nicht konfiguriert.": "lexwareApiKeyNotConfigured",
  "Lexware API key not configured. Set it in admin settings.": "lexwareApiKeyNotConfigured",
  "lexwareApiRequestFailed": "lexwareApiRequestFailed",
  "Lexware-API-Anfrage fehlgeschlagen: {detail}": "lexwareApiRequestFailed",
  "Lexware API request failed: {detail}": "lexwareApiRequestFailed",
  "lexwarePdfDownloadFailed": "lexwarePdfDownloadFailed",
  "PDF-Download fehlgeschlagen: {status}": "lexwarePdfDownloadFailed",
  "Failed to download PDF: {status}": "lexwarePdfDownloadFailed",
  "lexwareCreditNotePdfDownloadFailed": "lexwareCreditNotePdfDownloadFailed",
  "Gutschrift-PDF-Download fehlgeschlagen: {status}": "lexwareCreditNotePdfDownloadFailed",
  "Failed to download credit note PDF: {status}": "lexwareCreditNotePdfDownloadFailed",
  "lexwareCreditNoteOnlyRefunded": "lexwareCreditNoteOnlyRefunded",
  "Nur erstattete Rechnungen können nachgeholt werden.": "lexwareCreditNoteOnlyRefunded",
  "Only refunded invoices can be backfilled.": "lexwareCreditNoteOnlyRefunded",
  "lexwareInvoiceNotLinked": "lexwareInvoiceNotLinked",
  "Keine Lexware-Rechnung verknüpft.": "lexwareInvoiceNotLinked",
  "No Lexware invoice linked.": "lexwareInvoiceNotLinked",
  "lexwareCreditNoteAlreadyExists": "lexwareCreditNoteAlreadyExists",
  "Lexware-Gutschrift existiert bereits.": "lexwareCreditNoteAlreadyExists",
  "Lexware credit note already exists.": "lexwareCreditNoteAlreadyExists",
  "invoiceWasNotPaid": "invoiceWasNotPaid",
  "Rechnung war nicht bezahlt.": "invoiceWasNotPaid",
  "Invoice was not paid.": "invoiceWasNotPaid",
  "adminInvoicesExcluded": "adminInvoicesExcluded",
  "Admin-Rechnungen sind ausgeschlossen.": "adminInvoicesExcluded",
  "Admin invoices are excluded.": "adminInvoicesExcluded",
  "lexwareNotEnabled": "lexwareNotEnabled",
  "Lexware ist nicht aktiviert.": "lexwareNotEnabled",
  "Lexware is not enabled.": "lexwareNotEnabled",
  "lexwareCreditNoteSkippedForZeroInvoice": "lexwareCreditNoteSkippedForZeroInvoice",
  "Für 0-€-Rechnungen wird keine Lexware-Gutschrift angelegt.": "lexwareCreditNoteSkippedForZeroInvoice",
  "No Lexware credit note is created for €0 invoices.": "lexwareCreditNoteSkippedForZeroInvoice",
  "netpointsBalanceCannotBeNegative": "netpointsBalanceCannotBeNegative",
  "NetPoints-Kontostand darf nicht negativ werden.": "netpointsBalanceCannotBeNegative",
  "NetPoints balance cannot become negative.": "netpointsBalanceCannotBeNegative",
  "payoutRequestNotFound": "payoutRequestNotFound",
  "Auszahlungsanfrage nicht gefunden.": "payoutRequestNotFound",
  "Payout request not found.": "payoutRequestNotFound",
  "payoutRequestInvalidStatus": "payoutRequestInvalidStatus",
  "Auszahlungsanfrage hat einen ungültigen Status.": "payoutRequestInvalidStatus",
  "Payout request has an invalid status.": "payoutRequestInvalidStatus",
  "insufficientWithdrawableBalance": "insufficientWithdrawableBalance",
  "Nicht genügend auszahlbares Guthaben.": "insufficientWithdrawableBalance",
  "Insufficient withdrawable balance.": "insufficientWithdrawableBalance",
  "signerNameRequired": "signerNameRequired",
  "Name des Unterzeichners ist erforderlich.": "signerNameRequired",
  "Signer name is required.": "signerNameRequired",
  "businessAccountOnly": "businessAccountOnly",
  "Nur für Geschäftskonten verfügbar.": "businessAccountOnly",
  "Business accounts only.": "businessAccountOnly",
  "dpaAlreadyActive": "dpaAlreadyActive",
  "AVV ist bereits aktiv.": "dpaAlreadyActive",
  "DPA is already active.": "dpaAlreadyActive",
  "noActiveDpaAgreement": "noActiveDpaAgreement",
  "Keine aktive AVV-Vereinbarung.": "noActiveDpaAgreement",
  "No active DPA agreement.": "noActiveDpaAgreement",
  "providerAdapterNotFound": "providerAdapterNotFound",
  "Provider-Adapter nicht gefunden: {type}": "providerAdapterNotFound",
  "Provider adapter not found: {type}": "providerAdapterNotFound",
  "providerModuleNotFound": "providerModuleNotFound",
  "Provider-Modul nicht gefunden: {type}": "providerModuleNotFound",
  "Provider module not found: {type}": "providerModuleNotFound",
  "providerNotFoundOrInactive": "providerNotFoundOrInactive",
  "Provider nicht gefunden oder inaktiv.": "providerNotFoundOrInactive",
  "Provider not found or inactive.": "providerNotFoundOrInactive",
  "providerNotFoundForService": "providerNotFoundForService",
  "Kein Provider für Service: {serviceId}": "providerNotFoundForService",
  "No provider for service: {serviceId}": "providerNotFoundForService",
  "proxmoxServiceDisabled": "proxmoxServiceDisabled",
  "Proxmox-Dienst ist deaktiviert.": "proxmoxServiceDisabled",
  "Proxmox service is disabled. Enable it in admin settings.": "proxmoxServiceDisabled",
  "proxmoxNoClusterConfigured": "proxmoxNoClusterConfigured",
  "Kein Proxmox-Cluster konfiguriert.": "proxmoxNoClusterConfigured",
  "No Proxmox cluster configured.": "proxmoxNoClusterConfigured",
  "proxmoxNoOnlineNodes": "proxmoxNoOnlineNodes",
  "Keine Online-Nodes verfügbar.": "proxmoxNoOnlineNodes",
  "No online nodes available.": "proxmoxNoOnlineNodes",
  "proxmoxNoFreeVmid": "proxmoxNoFreeVmid",
  "Keine freie VM-ID zwischen {min} und {max}.": "proxmoxNoFreeVmid",
  "No free VM ID found from {min} to {max}.": "proxmoxNoFreeVmid",
  "proxmoxNoFreeScsiSlot": "proxmoxNoFreeScsiSlot",
  "Kein freier SCSI-Slot auf der VM.": "proxmoxNoFreeScsiSlot",
  "No free SCSI slot on VM.": "proxmoxNoFreeScsiSlot",
  "proxmoxServiceNoMapping": "proxmoxServiceNoMapping",
  "Service hat keine Proxmox-Zuordnung.": "proxmoxServiceNoMapping",
  "Service has no Proxmox mapping.": "proxmoxServiceNoMapping",
  "proxmoxVmNotProvisioned": "proxmoxVmNotProvisioned",
  "VM ist noch nicht provisioniert.": "proxmoxVmNotProvisioned",
  "VM not provisioned yet.": "proxmoxVmNotProvisioned",
  "proxmoxProvisionFailed": "proxmoxProvisionFailed",
  "Provisionierung fehlgeschlagen: {detail}": "serviceProvisioningFailed",
  "Provision failed: {detail}": "serviceProvisioningFailed",
  "proxmoxStorageExpansionNotConfigured": "proxmoxStorageExpansionNotConfigured",
  "Kein Expansion-Storage für Typ {storageType} konfiguriert.": "proxmoxStorageExpansionNotConfigured",
  "No expansion storage for type {storageType} in any category config.": "proxmoxStorageExpansionNotConfigured",
  "proxmoxServiceNoProviderVm": "proxmoxServiceNoProviderVm",
  "Service hat keine Provider-VM.": "proxmoxServiceNoProviderVm",
  "Service has no provider VM.": "proxmoxServiceNoProviderVm",
  "proxmoxStorageServiceMissingConfig": "proxmoxStorageServiceMissingConfig",
  "Storage-Service fehlt sizeGb oder clusterId.": "proxmoxStorageServiceMissingConfig",
  "Storage service missing sizeGb or clusterId.": "proxmoxStorageServiceMissingConfig",
  "proxmoxAuthenticationFailed": "proxmoxAuthenticationFailed",
  "Proxmox-Authentifizierung fehlgeschlagen ({status}).": "proxmoxAuthenticationFailed",
  "Authentication failed ({status}).": "proxmoxAuthenticationFailed",
  "proxmoxApiTokenCreateFailed": "proxmoxApiTokenCreateFailed",
  "API-Token konnte nicht erstellt werden ({status}).": "proxmoxApiTokenCreateFailed",
  "Failed to create API token ({status}).": "proxmoxApiTokenCreateFailed",
  "proxmoxStorageNotFoundOnNode": "proxmoxStorageNotFoundOnNode",
  "Storage {storage} auf Node {node} nicht gefunden.": "proxmoxStorageNotFoundOnNode",
  "Storage {storage} not found on node {node}.": "proxmoxStorageNotFoundOnNode",
  "proxmoxIsoDownloadFailed": "proxmoxIsoDownloadFailed",
  "ISO-Download fehlgeschlagen: {detail}": "proxmoxIsoDownloadFailed",
  "ISO download failed: {detail}": "proxmoxIsoDownloadFailed",
  "proxmoxTaskTimedOut": "proxmoxTaskTimedOut",
  "Task {upid} nach {timeout}ms abgelaufen.": "proxmoxTaskTimedOut",
  "Task {upid} timed out after {timeout}ms.": "proxmoxTaskTimedOut",
  "proxmoxMissingNodeOrStorage": "proxmoxMissingNodeOrStorage",
  "Node oder Storage für Storage-Volume-Löschung fehlt.": "proxmoxMissingNodeOrStorage",
  "Missing node or storage for storage volume deletion.": "proxmoxMissingNodeOrStorage",
  "proxmoxMissingNodeForVmDeletion": "proxmoxMissingNodeForVmDeletion",
  "Node für VM-Löschung fehlt.": "proxmoxMissingNodeForVmDeletion",
  "Missing node for VM deletion.": "proxmoxMissingNodeForVmDeletion",
  "proxmoxNoVmOrStorageInOptions": "proxmoxNoVmOrStorageInOptions",
  "Keine VM-ID oder Storage-Volume in Service-Optionen.": "proxmoxNoVmOrStorageInOptions",
  "No VM ID or storage volume found in service options.": "proxmoxNoVmOrStorageInOptions",
  "proxmoxNoClusterIdInOptions": "proxmoxNoClusterIdInOptions",
  "Keine clusterId in Service-Optionen.": "proxmoxNoClusterIdInOptions",
  "No clusterId found in service options.": "proxmoxNoClusterIdInOptions",
  "proxmoxCloneLockTimeout": "proxmoxCloneLockTimeout",
  "Clone-Sperre konnte nicht erworben werden.": "proxmoxCloneLockTimeout",
  "Clone lock could not be acquired.": "proxmoxCloneLockTimeout",
  "proxmoxVmidAllocationFailed": "proxmoxVmidAllocationFailed",
  "VMID-Zuweisung fehlgeschlagen.": "proxmoxVmidAllocationFailed",
  "VMID allocation failed.": "proxmoxVmidAllocationFailed",
  "invalidProxmoxExternalId": "invalidProxmoxExternalId",
  "Ungültiges Proxmox-External-ID-Format: {externalId}": "invalidProxmoxExternalId",
  "Invalid Proxmox external ID format: {externalId}": "invalidProxmoxExternalId",
  "pterodactylNoClientApiKey": "pterodactylNoClientApiKey",
  "Kein Client-API-Key für Panel {panelId} konfiguriert.": "pterodactylNoClientApiKey",
  "No client API key configured for panel {panelId}.": "pterodactylNoClientApiKey",
  "pterodactylServiceMissingProductOrSubscription": "pterodactylServiceMissingProductOrSubscription",
  "Service fehlt Produkt oder Subscription.": "pterodactylServiceMissingProductOrSubscription",
  "Service missing product or subscription.": "pterodactylServiceMissingProductOrSubscription",
  "pterodactylNoPanelAvailable": "pterodactylNoPanelAvailable",
  "Kein Pterodactyl-Panel verfügbar.": "pterodactylNoPanelAvailable",
  "No Pterodactyl panel available.": "pterodactylNoPanelAvailable",
  "pterodactylEggNotFound": "pterodactylEggNotFound",
  "Egg {eggId} in Kategorie-Konfiguration nicht gefunden.": "pterodactylEggNotFound",
  "Egg {eggId} not found in category configuration.": "pterodactylEggNotFound",
  "pterodactylServiceNoProviderServer": "pterodactylServiceNoProviderServer",
  "Service hat keinen Provider-Server.": "pterodactylServiceNoProviderServer",
  "Service has no provider server.": "pterodactylServiceNoProviderServer",
  "pterodactylProviderServiceIdMissing": "pterodactylProviderServiceIdMissing",
  "Provider-Service-ID fehlt.": "pterodactylProviderServiceIdMissing",
  "Provider service ID missing.": "pterodactylProviderServiceIdMissing",
  "pterodactylPanelIdMissing": "pterodactylPanelIdMissing",
  "Panel-ID fehlt.": "pterodactylPanelIdMissing",
  "Panel ID missing.": "pterodactylPanelIdMissing",
  "pterodactylServerIdentifierMissing": "pterodactylServerIdentifierMissing",
  "Server-Identifier fehlt.": "pterodactylServerIdentifierMissing",
  "Server identifier missing.": "pterodactylServerIdentifierMissing",
  "pterodactylUpgradeFailed": "pterodactylUpgradeFailed",
  "Upgrade fehlgeschlagen: {detail}": "pterodactylUpgradeFailed",
  "Upgrade failed: {detail}": "pterodactylUpgradeFailed",
  "pterodactylApiError": "pterodactylApiError",
  "Pterodactyl-API-Fehler: {detail}": "pterodactylApiError",
  "Pterodactyl API error: {detail}": "pterodactylApiError",
  "ipDnsIpv6ReverseZoneMissing": "ipDnsIpv6ReverseZoneMissing",
  "Reverse-Zone für IPv6-PTR fehlt.": "ipDnsIpv6ReverseZoneMissing",
  "Reverse zone for IPv6 PTR is missing.": "ipDnsIpv6ReverseZoneMissing",
  "ipDnsIpv4ReverseZoneMissing": "ipDnsIpv4ReverseZoneMissing",
  "Reverse-Zone für IPv4-PTR fehlt.": "ipDnsIpv4ReverseZoneMissing",
  "Reverse zone for IPv4 PTR is missing.": "ipDnsIpv4ReverseZoneMissing",
  "ipDnsInvalidIpv4ForPtr": "ipDnsInvalidIpv4ForPtr",
  "Ungültige IPv4 für PTR: {address}": "ipDnsInvalidIpv4ForPtr",
  "Invalid IPv4 for PTR: {address}": "ipDnsInvalidIpv4ForPtr",
  "ipDnsInvalidCidrForPtr": "ipDnsInvalidCidrForPtr",
  "Ungültiges CIDR für PTR: {cidr}": "ipDnsInvalidCidrForPtr",
  "Invalid CIDR for PTR: {cidr}": "ipDnsInvalidCidrForPtr",
  "ipDnsPtrContentRequired": "ipDnsPtrContentRequired",
  "PTR-Inhalt ist erforderlich.": "ipDnsPtrContentRequired",
  "PTR content is required.": "ipDnsPtrContentRequired",
  "ipDnsRecordNotFound": "ipDnsRecordNotFound",
  "DNS-Eintrag nicht gefunden.": "ipDnsRecordNotFound",
  "Record not found.": "ipDnsRecordNotFound",
  "ipDnsPowerDnsApiKeyMissing": "ipDnsPowerDnsApiKeyMissing",
  "IP-DNS PowerDNS API-Key nicht konfiguriert.": "ipDnsPowerDnsApiKeyMissing",
  "IP-DNS PowerDNS API key not configured.": "ipDnsPowerDnsApiKeyMissing",
  "ipDnsInvalidPowerDnsRecordId": "ipDnsInvalidPowerDnsRecordId",
  "Ungültige PowerDNS Record-ID (PTR).": "ipDnsInvalidPowerDnsRecordId",
  "Invalid PowerDNS record ID (PTR).": "ipDnsInvalidPowerDnsRecordId",
  "ipamSourceRangeIpv4NotFound": "ipamSourceRangeIpv4NotFound",
  "Quellbereich IPv4 nicht gefunden.": "ipamSourceRangeIpv4NotFound",
  "Source IPv4 range not found.": "ipamSourceRangeIpv4NotFound",
  "ipamInvalidIpv4BaseAddress": "ipamInvalidIpv4BaseAddress",
  "Ungültige IPv4-Basisadresse.": "ipamInvalidIpv4BaseAddress",
  "Invalid IPv4 base address.": "ipamInvalidIpv4BaseAddress",
  "ipamInvalidIpv4Cidr": "ipamInvalidIpv4Cidr",
  "IPv4-CIDR muss zwischen 1 und 30 liegen.": "ipamInvalidIpv4Cidr",
  "IPv4 CIDR must be between 1 and 30.": "ipamInvalidIpv4Cidr",
  "ipamTargetRangeIpv4Exists": "ipamTargetRangeIpv4Exists",
  "Zielbereich IPv4 existiert bereits.": "ipamTargetRangeIpv4Exists",
  "Target IPv4 range already exists.": "ipamTargetRangeIpv4Exists",
  "ipamSourceRangeIpv6NotFound": "ipamSourceRangeIpv6NotFound",
  "Quellbereich IPv6 nicht gefunden.": "ipamSourceRangeIpv6NotFound",
  "Source IPv6 range not found.": "ipamSourceRangeIpv6NotFound",
  "ipamInvalidIpv6BaseAddress": "ipamInvalidIpv6BaseAddress",
  "Ungültige IPv6-Basisadresse.": "ipamInvalidIpv6BaseAddress",
  "Invalid IPv6 base address.": "ipamInvalidIpv6BaseAddress",
  "ipamInvalidIpv6Cidr": "ipamInvalidIpv6Cidr",
  "IPv6-CIDR ungültig.": "ipamInvalidIpv6Cidr",
  "Invalid IPv6 CIDR.": "ipamInvalidIpv6Cidr",
  "ipamSplitIntoMustBeGteCidr": "ipamSplitIntoMustBeGteCidr",
  "splitInto muss >= cidr sein.": "ipamSplitIntoMustBeGteCidr",
  "splitInto must be >= cidr.": "ipamSplitIntoMustBeGteCidr",
  "ipamTargetRangeIpv6Exists": "ipamTargetRangeIpv6Exists",
  "Zielbereich IPv6 existiert bereits.": "ipamTargetRangeIpv6Exists",
  "Target IPv6 range already exists.": "ipamTargetRangeIpv6Exists",
  "ipamNoFreeIpv4InTargetRange": "ipamNoFreeIpv4InTargetRange",
  "Keine freie IPv4 im Zielbereich für {ip}.": "ipamNoFreeIpv4InTargetRange",
  "No free IPv4 in target range for {ip}.": "ipamNoFreeIpv4InTargetRange",
  "ipamIpv6SubnetCalculationFailed": "ipamIpv6SubnetCalculationFailed",
  "IPv6-Subnetz konnte nicht berechnet werden.": "ipamIpv6SubnetCalculationFailed",
  "IPv6 subnet could not be calculated.": "ipamIpv6SubnetCalculationFailed",
  "ipamNoFreeIpv6Subnet": "ipamNoFreeIpv6Subnet",
  "Kein freies IPv6-Subnetz im Zielbereich.": "ipamNoFreeIpv6Subnet",
  "No free IPv6 subnet in target range.": "ipamNoFreeIpv6Subnet",
  "ipamRemoveAtMustBeFutureDate": "ipamRemoveAtMustBeFutureDate",
  "removeAt muss ein gültiges Datum in der Zukunft sein.": "ipamRemoveAtMustBeFutureDate",
  "removeAt must be a valid date in the future.": "ipamRemoveAtMustBeFutureDate",
  "ipamIpv4AssignmentFailed": "ipamIpv4AssignmentFailed",
  "IPv4-Zuweisung fehlgeschlagen.": "ipamIpv4AssignmentFailed",
  "IPv4 assignment failed.": "ipamIpv4AssignmentFailed",
  "ipamSecondaryIpv4Failed": "ipamSecondaryIpv4Failed",
  "Sekundär-IPv4-Zuweisung fehlgeschlagen.": "ipamSecondaryIpv4Failed",
  "Secondary IPv4 assignment failed.": "ipamSecondaryIpv4Failed",
  "powerDnsMigrateSourceTargetIdentical": "powerDnsMigrateSourceTargetIdentical",
  "Quelle und Ziel dürfen nicht identisch sein.": "powerDnsMigrateSourceTargetIdentical",
  "Source and target must not be identical.": "powerDnsMigrateSourceTargetIdentical",
  "domainrobotLoginNotConfigured": "domainrobotLoginNotConfigured",
  "Domainrobot-Login nicht konfiguriert.": "domainrobotLoginNotConfigured",
  "Domainrobot login not configured.": "domainrobotLoginNotConfigured",
  "domainrobotLoginFailed": "domainrobotLoginFailed",
  "Domainrobot-Login fehlgeschlagen: {detail}": "domainrobotLoginFailed",
  "Domainrobot login failed: {detail}": "domainrobotLoginFailed",
  "domainrobotLoginNoToken": "domainrobotLoginNoToken",
  "Domainrobot-Login: Antwort enthält kein Token.": "domainrobotLoginNoToken",
  "Domainrobot login: response contains no token.": "domainrobotLoginNoToken",
  "domainrobotPricingInvalidResponse": "domainrobotPricingInvalidResponse",
  "Domainrobot Pricing: Ungültige Antwort.": "domainrobotPricingInvalidResponse",
  "Domainrobot pricing: invalid response.": "domainrobotPricingInvalidResponse",
  "domainrobotPricingNoData": "domainrobotPricingNoData",
  "Domainrobot Pricing: Kein data[].": "domainrobotPricingNoData",
  "Domainrobot pricing: no data[].": "domainrobotPricingNoData",
  "domainResellerPricingEmpty": "domainResellerPricingEmpty",
  "Reseller-Pricing: leere Antwort.": "domainResellerPricingEmpty",
  "Reseller pricing: empty response.": "domainResellerPricingEmpty",
  "cryptoEncryptionKeyMissing": "cryptoEncryptionKeyMissing",
  "Verschlüsselungsschlüssel fehlt oder ist ungültig.": "cryptoEncryptionKeyMissing",
  "Encryption key is missing or invalid.": "cryptoEncryptionKeyMissing",
  "cryptoCannotEncryptEmpty": "cryptoCannotEncryptEmpty",
  "Leerer Wert kann nicht verschlüsselt werden.": "cryptoCannotEncryptEmpty",
  "Cannot encrypt empty value.": "cryptoCannotEncryptEmpty",
  "cryptoEncryptFailed": "cryptoEncryptFailed",
  "Verschlüsselung fehlgeschlagen.": "cryptoEncryptFailed",
  "Failed to encrypt value.": "cryptoEncryptFailed",
  "cryptoCannotDecryptEmpty": "cryptoCannotDecryptEmpty",
  "Leerer Wert kann nicht entschlüsselt werden.": "cryptoCannotDecryptEmpty",
  "Cannot decrypt empty value.": "cryptoCannotDecryptEmpty",
  "cryptoInvalidEncryptedFormat": "cryptoInvalidEncryptedFormat",
  "Ungültiges verschlüsseltes Datenformat.": "cryptoInvalidEncryptedFormat",
  "Invalid encrypted data format.": "cryptoInvalidEncryptedFormat",
  "cryptoInvalidIvLength": "cryptoInvalidIvLength",
  "Ungültige IV-Länge.": "cryptoInvalidIvLength",
  "Invalid IV length.": "cryptoInvalidIvLength",
  "cryptoInvalidAuthTagLength": "cryptoInvalidAuthTagLength",
  "Ungültige Auth-Tag-Länge.": "cryptoInvalidAuthTagLength",
  "Invalid auth tag length.": "cryptoInvalidAuthTagLength",
  "cryptoDecryptFailed": "cryptoDecryptFailed",
  "Entschlüsselung fehlgeschlagen. Daten möglicherweise beschädigt.": "cryptoDecryptFailed",
  "Failed to decrypt value. Data may be corrupted or encrypted with a different key.": "cryptoDecryptFailed",
  "appKeyRequired": "appKeyRequired",
  "APP_KEY ist erforderlich. Führen Sie \"bun run key:generate\" aus.": "appKeyRequired",
  "APP_KEY is required. Run \"bun run key:generate\" to create one.": "appKeyRequired",
  "appKeyInvalidFormat": "appKeyInvalidFormat",
  "APP_KEY hat ein ungültiges Format.": "appKeyInvalidFormat",
  "APP_KEY has an invalid format.": "appKeyInvalidFormat",
  "environmentValidationFailed": "environmentValidationFailed",
  "Umgebungsvalidierung fehlgeschlagen: {detail}": "environmentValidationFailed",
  "Environment validation failed: {detail}": "environmentValidationFailed",
  "checkoutDomainActionMissingOrderId": "checkoutDomainActionMissingOrderId",
  "Domain-Aktion ohne Action-Order-ID.": "checkoutDomainActionMissingOrderId",
  "Domain action without action order ID.": "checkoutDomainActionMissingOrderId",
  "smartUpgradeNoServiceLinked": "smartUpgradeNoServiceLinked",
  "Kein Service mit Subscription verknüpft.": "smartUpgradeNoServiceLinked",
  "No service linked to subscription.": "smartUpgradeNoServiceLinked",
  "smartUpgradeFailedToParseOptions": "smartUpgradeFailedToParseOptions",
  "Service-Optionen konnten nicht geparst werden.": "smartUpgradeFailedToParseOptions",
  "Failed to parse service options.": "smartUpgradeFailedToParseOptions",
  "deferredReinstallFailed": "deferredReinstallFailed",
  "Reinstall fehlgeschlagen: {detail}": "deferredReinstallFailed",
  "Reinstall failed: {detail}": "deferredReinstallFailed",
  "serviceProvisioningFailed": "serviceProvisioningFailed",
  "cloudInitNoSshKeys": "cloudInitNoSshKeys",
  "Keine SSH-Keys für diesen Service hinterlegt.": "cloudInitNoSshKeys",
  "No SSH keys configured for this service.": "cloudInitNoSshKeys",
  "discordBotTokenNotConfigured": "discordBotTokenNotConfigured",
  "Discord-Bot-Token nicht konfiguriert.": "discordBotTokenNotConfigured",
  "Discord bot token not configured.": "discordBotTokenNotConfigured",
  "discordApiError": "discordApiError",
  "Discord-API-Fehler: {detail}": "discordApiError",
  "Discord API error: {detail}": "discordApiError",
  "ssoMissingOidcEndpoints": "ssoMissingOidcEndpoints",
  "SSO-Provider hat weder Endpunkte noch Issuer für Discovery.": "ssoMissingOidcEndpoints",
  "SSO provider has neither explicit endpoints nor an issuer for discovery.": "ssoMissingOidcEndpoints",
  "ssoOidcDiscoveryFailed": "ssoOidcDiscoveryFailed",
  "OIDC-Discovery fehlgeschlagen: {status}": "ssoOidcDiscoveryFailed",
  "OIDC discovery failed: {status}": "ssoOidcDiscoveryFailed",
  "ssoOidcMissingEndpoints": "ssoOidcMissingEndpoints",
  "OIDC-Discovery-Dokument fehlt erforderliche Endpunkte.": "ssoOidcMissingEndpoints",
  "OIDC discovery document is missing required endpoints.": "ssoOidcMissingEndpoints",
  "ssoOidcTokenExchangeFailed": "ssoOidcTokenExchangeFailed",
  "OIDC-Token-Austausch fehlgeschlagen: {status}": "ssoOidcTokenExchangeFailed",
  "OIDC token exchange failed: {status}": "ssoOidcTokenExchangeFailed",
  "ssoOidcUserinfoFailed": "ssoOidcUserinfoFailed",
  "OIDC-Userinfo fehlgeschlagen: {status}": "ssoOidcUserinfoFailed",
  "OIDC userinfo failed: {status}": "ssoOidcUserinfoFailed",
  "ssoOidcMissingSubject": "ssoOidcMissingSubject",
  "OIDC-Userinfo enthält kein Subject.": "ssoOidcMissingSubject",
  "OIDC userinfo missing subject.": "ssoOidcMissingSubject",
  "powerDnsApiKeyNotConfigured": "powerDnsApiKeyNotConfigured",
  "PowerDNS API-Key nicht konfiguriert.": "powerDnsApiKeyNotConfigured",
  "PowerDNS API key not configured.": "powerDnsApiKeyNotConfigured",
  "autoTopupInvalidTimezone": "autoTopupInvalidTimezone",
  "Ungültige Zeitzone für Auto-Top-up: {tz}": "autoTopupInvalidTimezone",
  "Invalid timezone for auto top-up: {tz}": "autoTopupInvalidTimezone",
  "autoTopupNextChargeDateFailed": "autoTopupNextChargeDateFailed",
  "Nächstes Abbuchungsdatum konnte nicht berechnet werden.": "autoTopupNextChargeDateFailed",
  "Failed to compute next charge date.": "autoTopupNextChargeDateFailed",
  "pushInvalidSubscriptionEndpoint": "pushInvalidSubscriptionEndpoint",
  "Ungültiger Push-Subscription-Endpunkt.": "pushInvalidSubscriptionEndpoint",
  "Invalid subscription endpoint.": "pushInvalidSubscriptionEndpoint",
  "deviceTokenRequired": "deviceTokenRequired",
  "deviceToken ist erforderlich.": "deviceTokenRequired",
  "deviceToken is required.": "deviceTokenRequired",
  "invalidDateOnlyString": "invalidDateOnlyString",
  "Ungültiger Datums-String: {value}": "invalidDateOnlyString",
  "Invalid date-only string: {value}": "invalidDateOnlyString",
  "invalidMonthKey": "invalidMonthKey",
  "Ungültiger Monatsschlüssel.": "invalidMonthKey",
  "Invalid month key.": "invalidMonthKey",
  "hosterCheckPackageTypeUnresolved": "hosterCheckPackageTypeUnresolved",
  "hoster-check.at-Pakettyp für Kategorie \"{category}\" nicht auflösbar.": "hosterCheckPackageTypeUnresolved",
  "hoster-check.at package type could not be resolved for category \"{category}\".": "hosterCheckPackageTypeUnresolved",
  "targetMarginPercentTooHigh": "targetMarginPercentTooHigh",
  "targetMarginPercent zu hoch.": "targetMarginPercentTooHigh",
  "targetMarginPercent too high.": "targetMarginPercentTooHigh",
  "elizonPlusRolloutDisabled": "elizonPlusRolloutDisabled",
  "elizon+-Rollout ist deaktiviert.": "elizonPlusRolloutDisabled",
  "elizon+ rollout is disabled.": "elizonPlusRolloutDisabled",
  "webauthnRegistrationFailed": "webauthnRegistrationFailed",
  "Passkey-Registrierung fehlgeschlagen.": "webauthnRegistrationFailed",
  "Passkey registration verification failed.": "webauthnRegistrationFailed",
  "webauthnAuthenticationFailed": "webauthnAuthenticationFailed",
  "Passkey-Authentifizierung fehlgeschlagen.": "webauthnAuthenticationFailed",
  "Passkey authentication verification failed.": "webauthnAuthenticationFailed",
  "wsConnectionUrlRequired": "wsConnectionUrlRequired",
  "URL ist für WebSocket-Verbindung erforderlich.": "wsConnectionUrlRequired",
  "A URL is required to establish a WebSocket connection.": "wsConnectionUrlRequired",
  "otpauthInvalidString": "otpauthInvalidString",
  "Ungültiger otpauth://-String: {detail}": "otpauthInvalidString",
  "Invalid otpauth:// string: {detail}": "otpauthInvalidString",
  "otpauthUnknownType": "otpauthUnknownType",
  "Unbekannter OTPAuth-Typ (nur TOTP/HOTP unterstützt).": "otpauthUnknownType",
  "Unknown OTPAuth type (only TOTP/HOTP supported).": "otpauthUnknownType",
  "smtpCommandFailed": "smtpCommandFailed",
  "SMTP-Befehl fehlgeschlagen: {detail}": "smtpCommandFailed",
  "SMTP command failed: {detail}": "smtpCommandFailed",
  "unknownProviderAction": "unknownProviderAction",
  "Unbekannte Provider-Aktion: {action}": "unknownProviderAction",
  "Unknown action: {action}": "unknownProviderAction",
  "pricingProductOptionsInvalid": "pricingProductOptionsInvalid",
  "Ungültige Produktoptionen: {detail}": "pricingProductOptionsInvalid",
  "Invalid product options: {detail}": "pricingProductOptionsInvalid",
  "tbWalletOperationFailed": "tbWalletOperationFailed",
  "TB-Wallet-Operation fehlgeschlagen: {detail}": "tbWalletOperationFailed",
  "TB wallet operation failed: {detail}": "tbWalletOperationFailed",
  "mailcowOperationFailed": "mailcowOperationFailed",
  "Mailcow-Operation fehlgeschlagen: {detail}": "mailcowOperationFailed",
  "Mailcow operation failed: {detail}": "mailcowOperationFailed",
  "floatingIpOperationFailed": "floatingIpOperationFailed",
  "Floating-IP-Operation fehlgeschlagen: {detail}": "floatingIpOperationFailed",
  "Floating IP operation failed: {detail}": "floatingIpOperationFailed",
  "vmImportFailed": "vmImportFailed",
  "VM-Import fehlgeschlagen: {detail}": "vmImportFailed",
  "VM import failed: {detail}": "vmImportFailed",
  "monthlyOffersConfigInvalid": "monthlyOffersConfigInvalid",
  "Monatsangebote-Konfiguration ungültig.": "monthlyOffersConfigInvalid",
  "Monthly offers configuration invalid.": "monthlyOffersConfigInvalid",
  "productPromotionInvalid": "productPromotionInvalid",
  "Produktaktion ungültig: {detail}": "productPromotionInvalid",
  "Product promotion invalid: {detail}": "productPromotionInvalid",
  "autopayOperationFailed": "autopayOperationFailed",
  "Autopay-Operation fehlgeschlagen: {detail}": "autopayOperationFailed",
  "Autopay operation failed: {detail}": "autopayOperationFailed",
  "ipFlowMetricsInvalidIpv4": "ipFlowMetricsInvalidIpv4",
  "Ungültige IPv4-Adresse: {ip}": "ipFlowMetricsInvalidIpv4",
  "Invalid IPv4 address: {ip}": "ipFlowMetricsInvalidIpv4",
  "ipFlowMetricsInvalidOctet": "ipFlowMetricsInvalidOctet",
  "Ungültiges Oktett: {octet}": "ipFlowMetricsInvalidOctet",
  "Invalid octet: {octet}": "ipFlowMetricsInvalidOctet",
  "insufficientNetPoints": "insufficientNetPoints",
  "Nicht genügend NetPoints.": "insufficientNetPoints",
  "Insufficient NetPoints.": "insufficientNetPoints"
};
